# -*- coding: utf-8 -*-
"""overpass_chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFIdFMC-XAAY3mYWUTDw-DTzGyH-U1_l
"""

import requests
import itchat
 
KEY ='**************************' #KEY is the api key of Turing robot, you can go to the official website to apply
 
def get_response(msg):
    apiUrl = 'http://www.tuling123.com/openapi/api'
    data = {
        'userid' : 'wechat-robot',
        'key'    : KEY,
        'info'   : msg,
    }
    try:
        r = requests.post(apiUrl, data=data).json()
        return r.get('text')
    except:
        return
 
 
@itchat.msg_register(itchat.content.TEXT)
def tuling_reply(msg):
    defaultReply = 'I received: ' + msg['Text']
    reply = get_response(msg['Text'])
    return reply or defaultReply
 
 
itchat.auto_login(hotReload=True)
itchat.run()